import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [2]:
import numpy as np


In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [4]:
# How many negative numbers are there?
# a[a < 0] gives the negatives
print(a[a < 0])
len(a[a < 0])


[-2 -1 -6 -7]


4

In [5]:
# How many positive numbers are there?

a>0
a[a>0].size

5

In [6]:
# How many positive numbers are there?

a[a>0].size

5

In [7]:
# If you were to add 3 to each data point, how many positive numbers would there be?

a[(a % 2 == 0) & (a > 0)].size


3

In [8]:
# The output does not reassign the value associated with the variable name add_three

add_three = a+3
add_three[add_three > 0].size


10

In [9]:
# If you squared each number, what would the new mean and standard deviation be?

squared = a ** 2
print(f"Mean: {squared.mean()}")
print(f"Standard Deviation: {squared.std()}")

Mean: 74.0
Standard Deviation: 144.0243035046516


In [10]:
# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

centered = a - a.mean()
centered
centered.mean()


0.0

In [11]:
# Calculate the z-score for each data point.

zscores = (a - a.mean()) / a.std()
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [10]:
# Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

sum_of_a = sum(a)
sum_of_a

55

In [5]:
# Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
min_of_a

1

In [6]:
# Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [7]:
# Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [8]:
# Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for n in a:
    product_of_a = product_of_a * n

product_of_a

3628800

In [9]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n**2 for n in a]
squares_of_a

[16, 100, 144, 529, 4, 1, 0, 0, 0, 36, 9, 49]

In [11]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a


[1, 3, 5, 7, 9]

In [12]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a


[2, 4, 6, 8, 10]

In [13]:
# Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [[3, 4, 5],
    [6, 7, 8]]


flattened_list = []
for numbers in b:
    for n in numbers:
        flattened_list.append(n)
flattened_list

[3, 4, 5, 6, 7, 8]

In [14]:
output = {
    "sum": sum(flattened_list),
    "min": min(flattened_list),
    "max": max(flattened_list),
    "avg": sum(flattened_list) / len(flattened_list),
    "squares": [n**2 for n in flattened_list]
}
output

{'sum': 33, 'min': 3, 'max': 8, 'avg': 5.5, 'squares': [9, 16, 25, 36, 49, 64]}

Numpy Key Takeaways (transfer to Pandas seamslessly)
Vectorized operations with comparison operators ==, >, >=, etc..
Vectorized operations for mathematical operators like *, +, /, etc...
We use arrays of booleans (usually produced by comparison operators) to filter our arrays of data
 